### ISSUE TITLE
Different error codes for denied permissions.

### ISSUE THREAD

**Issue by ramanbranavitski** [miguelbcr/RxPaparazzo#32]
It would be great if you add different resultCode when user denied permission with checked "Do not ask again" or not. I know that it issue most suitable for RxPaparazzo, but may be you can add this feature locally.

**Comment by miguelbcr** [comment]
Hi @ramanbranavitski !
If you don't mind,  you could do a Pull Request with this feature.

**Comment by ramanbranavitski** [comment]
@miguelbcr created issue for RxPermissions. They will implement this feature.
https://github.com/tbruyelle/RxPermissions/issues/68

**Comment by ramanbranavitski** [comment]
Hi @miguelbcr, they've implemented this feature. Can you add it into your project?

**Comment by miguelbcr** [comment]
Hi @ramanbranavitski !
I'll try to do this this weekend.

**Comment by ramanbranavitski** [comment]
It will be great. Thank you. Let me know about your result.

**Comment by miguelbcr** [comment]
Hi @ramanbranavitski ,
Ive released versions [0.4.2](https://github.com/miguelbcr/RxPaparazzo/releases/tag/0.4.2) and [0.4.2-2-x](https://github.com/miguelbcr/RxPaparazzo/releases/tag/0.4.2-2.x)

The commits related are (I made a mistake referenced the issue when I commited them):
RxJava1 > 8d37b80347ea904f6fd3ca7d2bd872414b33f8dd
RxJava2 > acfdd2ac910d34897a1b4a4fdcdc15028ee6e803

Try it out and let me know,

**Comment by ramanbranavitski** [comment]
Hi, @miguelbcr. I've tested new version of library. Works as expected. Thank you very much.
