### ISSUE TITLE
Resize image to custom size.

### ISSUE THREAD

**Issue by ramanbranavitski** [miguelbcr/RxPaparazzo#35]
It will be very fine if you add possibility to resize image to any custom size. Now, you have such possibility. The most suitable size now is Screen, but if we use app on tablets and phones this size type is not exactly what users of this library want. I create pull request for this feature.

**Comment by ramanbranavitski** [comment]
So, how can I use updated version of library?

2016-08-26 10:04 GMT+03:00 miguelbcr <notifications@github.com>:

**Comment by miguelbcr** [comment]
Ready new [release 0.2.1](https://github.com/miguelbcr/RxPaparazzo/releases/tag/0.2.1) !

**Comment by ramanbranavitski** [comment]
Thanks)

2016-08-26 11:07 GMT+03:00 miguelbcr <notifications@github.com>:
