### ISSUE TITLE
Proguard rules

### ISSUE THREAD

**Issue by GediminasZukas** [miguelbcr/RxPaparazzo#36]
I am using proguard in my project. What kind of proguard rules should I add in my proguard file to avoid all the warnings and crashes? Can you include description in library readme file?

Currently I am getting such crash when using RxPaparazzo with proguard:

```
Crashed: main: 0 0 0x0000000000000000
       at rx.internal.util.unsafe.UnsafeAccess.addressOf(UnsafeAccess.java:109)
       at rx.internal.util.unsafe.MpmcArrayQueueProducerField.(MpmcArrayQueue.java:31)
       at rx.internal.util.ObjectPool.initialize(ObjectPool.java:153)
       at rx.internal.util.ObjectPool.(ObjectPool.java:57)
       at rx.internal.util.ObjectPool.(ObjectPool.java:36)
       at rx.internal.util.RxRingBuffer$1.(RxRingBuffer.java:280)
       at rx.internal.util.RxRingBuffer.(RxRingBuffer.java:280)
```

**Comment by miguelbcr** [comment]
Hi @GediminasZukas ,
sorry but now I don't use Proguard so I don't know what rules would work.

You can try something like this:
`-keep class com.fuck_boilerplate.rx_paparazzo.** { *; }`

If you find out something let me know to add it to README. I'll do the same

**Comment by GediminasZukas** [comment]
@miguelbcr , seems I found the solution. The problem is not with RxPaparazzo itself but with its dependency (RxJava).

I just integrated this project into mine and everything works well: https://github.com/artem-zinnatullin/RxJavaProGuardRules  

Alternatively, it is possible to add these lines in proguard file and everything seems to work (as far as I tested):

```
# Rxjava rules
-dontwarn rx.internal.util.**

-keepclassmembers class rx.internal.util.unsafe.*ArrayQueue*Field* {
    long producerIndex;
    long consumerIndex;
}
-keepclassmembers class rx.internal.util.unsafe.BaseLinkedQueueProducerNodeRef {
    long producerNode;
    long consumerNode;
}
```

**Comment by miguelbcr** [comment]
Thank you very much @GediminasZukas !

I'm going to add those lines to README.
