### ISSUE TITLE
without lambda expression

### ISSUE THREAD

**Issue by MostafaEbrahimi** [miguelbcr/RxPaparazzo#43]
I have problem with java 8 in my android studio.
how can i use your lib in jdk 1.7 ?

**Comment by miguelbcr** [comment]
Hi @MostafaEbrahimi !,
The lib doesn't use lambda expressions but the sample app use them.

So, is your problem compiling the sample app or using the lib in your app?

Anyway I think it would be best for you to try to run java 8 in AS

**Comment by MostafaEbrahimi** [comment]
problem solved.thanks

**Comment by bms270** [comment]
How would you use the library without Lambda expression?
