### ISSUE TITLE
Doesn't work with facebook sdk on API 19

### ISSUE THREAD

**Issue by ZeRoGerc** [miguelbcr/RxPaparazzo#50]
If you include facebook sdk in project on android API 19 you get the following stacktrace while trying to perform register(this):

`0-12 17:20:34.161 16729-16729/com.zeroger.application E/dalvikvm: Could not find class 'rx_activity_result.RxActivityResult$Builder', referenced from method rx_activity_result.RxActivityResult.on
10-12 17:20:34.171 16729-16729/com.zeroger.application E/dalvikvm: Could not find class 'rx_activity_result.RxActivityResult$Builder', referenced from method rx_activity_result.RxActivityResult.on
10-12 17:20:34.171 16729-16729/com.zeroger.application E/dalvikvm: Could not find class 'rx_activity_result.ActivitiesLifecycleCallbacks', referenced from method rx_activity_result.RxActivityResult.register
10-12 17:20:34.171 16729-16729/com.zeroger.application E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: com.zeroger.application, PID: 16729
                                                                         java.lang.NoClassDefFoundError: rx_activity_result.ActivitiesLifecycleCallbacks
                                                                             at rx_activity_result.RxActivityResult.register(RxActivityResult.java:37)
                                                                             at com.fuck_boilerplate.rx_paparazzo.RxPaparazzo.register(RxPaparazzo.java:39)
                                                                             at com.zerogerc.application.model.ExperimentsApplication.onCreate(ExperimentsApplication.java:21)....`

This is occured not only on RxPaparzzo. RxActivityResult have the same issue. 
Could you propose possible fix?

**Comment by miguelbcr** [comment]
Hi @ZeRoGerc !
I've tried to reproduce the error but I haven't been able.

I've added these lines to gradle:
```
    compile "io.reactivex:rxjava:1.1.10"
    compile "com.github.miguelbcr:RxPaparazzo:0.3.2"
    compile 'com.facebook.android:facebook-android-sdk:[4,5)'
```

and this to my Application class:

``` java
public class BaseApp extends Application {
    @Override public void onCreate() {
        super.onCreate();
        RxPaparazzo.register(this);
    }
}
```

and I've launched the app on a device with API 19 and it hasn't crashed.

Please tell me if my sample app is correct or not. Anyway you could upload a sample app where the crash can be reproduced

**Comment by ZeRoGerc** [comment]
Check this app. It works correctly when I exclude facedook sdk
https://github.com/ZeRoGerc/android-experiments/tree/rxpaparazzio

**Comment by miguelbcr** [comment]
Hi @ZeRoGerc ,
I've tested the app and it crashes, indeed.

But I've seen that you have a lot of libraries in your `buil.gradle` which make that your `apk ` has a lot of methods, exactly `Total methods count: 66305 ` , so when it overtakes 64k you have to use [multidex](https://developer.android.com/studio/build/multidex.html) .

As far as I know, the problem is not related with `RxPaparazzo` but with the methods count, so you have 2 options (I've tested both of them and all of them work fine):

1. Reduce the method count by removing libraries that you not use or you can avoid. Check this [site](http://inloop.github.io/apk-method-count/) to know what packages have more methods.
2. Use [multidex](https://developer.android.com/studio/build/multidex.html) . Basically:

      Add it to your `build.gradle`:
       ```
android{ 
     ...
     defaultConfig {
        ....
       multiDexEnabled true
     }
     ....
}
...
dependencies {
  compile 'com.android.support:multidex:1.0.1'
}
```

    And `MultiDex.install(this);` in your `ExperimentsApplication`:
```
@Override public void onCreate() {
        super.onCreate();
        MultiDex.install(this);
        applicationComponent = initApplicationComponent();
        RxPaparazzo.register(this);
        RxActivityResult.register(this);
    }
```

I hope it helps you.

**Comment by ZeRoGerc** [comment]
I've forgot that on pre-lolipop it needs to invoke MultiDex.install(this) =)
Thanks.
