### ISSUE TITLE
Rxjava 2 support 

### ISSUE THREAD

**Issue by ReginFell** [miguelbcr/RxPaparazzo#51]
Is there plans to implement rxjava 2 support?

**Comment by miguelbcr** [comment]
Hi @ReginFell ,
yes, soon :), but lately I'm a bit busy.
Sorry.

**Comment by miguelbcr** [comment]
Hi @ReginFell !
I've released [version 0.4.1-2.x](https://github.com/miguelbcr/RxPaparazzo/releases/tag/0.4.1-2.x) with support for rxJava2.

If you find something wrong let me know.

**Comment by ReginFell** [comment]
Thanks a lot!
