### ISSUE TITLE
Losing data with horizontal camera

### ISSUE THREAD

**Issue by Yazon2006** [miguelbcr/RxPaparazzo#56]
I've just tested RxPaparazzo on Samsung Galaxy Note 2 and found an issue on activity orientation change. When device starts camera in horizontal orientation my activity also turns and destroys. When callback returns it leads to the destroyed activity. I decided to keep my activity alive on orientation change and used dirty hack android:configChanges="keyboardHidden|orientation|screenSize" because I don't have different resources for different orientation of screen.

@VictorAlbertos @miguelbcr do you think this bug related with samsung specific devices or all devices which has horizontal camera?

**Comment by miguelbcr** [comment]
Hi @Yazon2006 ,
Have you experience that behaviour with RxPaparazzo samples or with your app?

**Comment by Yazon2006** [comment]
@miguelbcr Good question.) I tried sample app and it does not have such issue.

**Comment by miguelbcr** [comment]
Hi @Yazon2006 ,
Have you figure out something?

**Comment by Yazon2006** [comment]
@miguelbcr I decided to leave android:configChanges="keyboardHidden|orientation|screenSize" on my activity as I haven't time to investigate this issue. As I said that your sample app works good. So that's why I think the problem is in my part of code. You can close issue. I'll back to that project later and if it necessary will reopen this thread.

**Comment by Yazon2006** [comment]
It was my fault. I used my fragment methods directly instead of response.targetUI(). Sorry for that and thank you for library ^_^

**Comment by miguelbcr** [comment]
😮  yeah, that's a common error 😄 
Don't worry 👍
