### ISSUE TITLE
Example on FileProvider

### ISSUE THREAD

**Issue by renegens** [miguelbcr/RxPaparazzo#64]
On the RxJava 2 branch the FileProvider is being used. When adding a custom file_provider there is no clear documentation how to obtain the file_provider 

Using this in the builder object is not working:
`.setFileProviderAuthority((BuildConfig.APPLICATION_ID + ".file_provider")`

`Failed to find configured root that contains /data/data/com.globyworks.citykey.debug/files/RxPaparazzo/PHOTO-20170302_1048_30638.jpg`

`<paths>
  <files-path
    name="CityKeyImages"
    path="CityKey/" />
</paths>`

**Comment by yakot93** [comment]
I found a solution. You need to add it 
```
 <provider
        android:name="android.support.v4.content.FileProvider"
        android:authorities="${applicationId}.file_provider"
        android:exported="false"
        android:grantUriPermissions="true">
      <meta-data
          android:name="android.support.FILE_PROVIDER_PATHS"
          android:resource="@xml/rx_paparazzo_file_paths"/>
 </provider>
```
in manifest.xml and create [here](https://github.com/miguelbcr/RxPaparazzo/blob/master/rx_paparazzo/src/main/res/xml/rx_paparazzo_file_paths.xml) such xml resource/

**Comment by renegens** [comment]
@yakot93 Yeah I have already done that.

**Comment by miguelbcr** [comment]
Hi @renegens,
you should use `RxPaparazzo.Builder.setFileProviderAuthority(String authority)` if your `android:authorities="${applicationId}.file_provider"` is not `file_provider"`

and you should use `RxPaparazzo.Builder.setFileProviderPath(String path)` if your `path` in `<files-path name="RxPaparazzoImages" path="RxPaparazzo/"/>` is not `RxPaparazzo`

I think you forgot to add `.setFileProviderPath("CityKey")`
Try it out and let me know if it works.

**Comment by renegens** [comment]
Hello @miguelbcr 
You are correct, my authorites was `android:authorities="${applicationId}.file_provider"` but I hadn't set the File provider path.
