### ISSUE TITLE
Setup instructions broken.

### ISSUE THREAD

**Issue by eliasbagley** [miguelbcr/RxPaparazzo#67]
Setup instructions seem broken to me. Gradle fails to resolve the library

**Comment by miguelbcr** [comment]
Hi @eliasbagley ,

I've just created a sample  project and it works fine.

Could you paste your compile statements you have used and the error output?

**Comment by eliasbagley** [comment]
I think the problem was I was putting the jitpack url in the app's build file, rather than the project build file. Thanks!
