### ISSUE TITLE
Do we really need to provide an activity or a fragment?

### ISSUE THREAD

**Issue by mradzinski** [miguelbcr/RxPaparazzo#69]
Hey Miguel, quick question over here: Is it truly needed to provide an activity or a fragment to RxPaparazzo? Shouldn't it suffice to provide an application context or a context itself? I understand you use the activity/fragment in the subscription, but as an example, If someone tries to use RxPaparazzo on a presenter (MVP), then the presenter would need to be aware of the Activity, thus breaking the whole MVP concept (Activity and Presenter should only communicate through the View the Activity implements, thus not be aware of each other). I guess a context overload should be available for this purposes where the developer doesn't care about the TargetUI at all because it already has a view (MVP).

Thanks for the awesome library an effort you put on it.

**Comment by miguelbcr** [comment]
Hi @mradzinski !
Thanks! it was also an effort of @VictorAlbertos  and @JM-Agrimap 

According to doc and [RxActivityResult](https://github.com/VictorAlbertos/RxActivityResult) we have that:

> This instance ([Response object](https://github.com/miguelbcr/RxPaparazzo/blob/2.x/rx_paparazzo/src/main/java/com/miguelbcr/ui/rx_paparazzo2/entities/Response.java)) holds a reference to the current Activity/Fragment, accessible calling targetUI() method. Because the original one may be recreated it would be unsafe calling it. Instead, you must call any method/variable of your Activity/Fragment from this instance encapsulated in the response instance.

Regarding to MVP pattern, you could delegate RxPaparazzo's launching to the Activity/Fragment  in this way:

```java
interface ActivityView {

      Observable<String> takeImage();

      Observable<List<String>> takeImage();
}
```

so the `Activity` will implement those methods such as:

```java
class Activity implements ActivityView {

      ...

      Observable<String> takeImage() {
            return RxPaparazzo.single(this)
                 .usingCamera()
                 .subscribeOn(Schedulers.io())
                 .observeOn(AndroidSchedulers.mainThread())
                 .map(response -> {
                      // See response.resultCode() doc
                      if (response.resultCode() != RESULT_OK) {
                         response.targetUI().showUserCanceled();
                         return "";
                      }

                      return response.data().getFile().getAbsolutePath();
                });
          }

      ...
}
```
and the presenter will interact with the view without be aware of the `Activity/Fragment`:



```java
class ActivityPresenter {

      // At some point of your code
      view.takeImage().subscribe(filePath -> {
             view.loadImage(filePath);
      }

}
```

**Comment by mradzinski** [comment]
Do'h! The obviousness of my question escapes my own understanding! in my defense: It was 3:00 AM 😂 . Closing this for good. Thanks @miguelbcr
