### ISSUE TITLE
Could not change the path for saving files

### ISSUE THREAD

**Issue by aalexsanyan** [miguelbcr/RxPaparazzo#74]
I want to change  the path
<paths>
    <files-path
        name="RxPaparazzoImages"
        path="RxPaparazzo/"/>
</paths>
and put my application name, but adding RxPaparazzo.Builder.setFileProviderPath(String path)
doesn't work as RxPaparazzo doesn't have Builder
and I'm using
 compile "com.github.miguelbcr:RxPaparazzo:0.5.4-2.x"

**Comment by miguelbcr** [comment]
Hi @aalexsanyan 
you need change this in your `Application` class:
```java

        RxPaparazzo.register(this)
            .withFileProviderPath("MyAppPhotos");
``` 

and this in your `rx_paparazzo_file_paths.xml` file:

```xml
<?xml version="1.0" encoding="utf-8"?>
<paths>
  <files-path
      name="MyAppPhotosImages"
      path="MyAppPhotos/"/>
</paths>
```

And that will create the `MyAppPhotos` folder in your root file system

**Comment by aalexsanyan** [comment]
Thanks
