### ISSUE TITLE
How to pick photo from gallery without making copy of  it?

### ISSUE THREAD

**Issue by aalexsanyan** [miguelbcr/RxPaparazzo#75]
1.I want to choose pick a image from gallery and display it without cropping and that is why I'm passing null for options  pickSingle(null, OriginalSize())
but I see it saves the copy of existing file as I try to pick a new one I see the copied version of my original photo , I mean if I want to display existing photo I don't want to have the copied version.

2 When I'm want to change the photo as a result of picking a photo (it opens the Recent folder) navigating to Photos and to the RxPaparazzo folder it displays the count 5 photos (the copied versions as well ),but when I navigate inside the folder only the original ones,not copied photos

**Comment by miguelbcr** [comment]
Hi @aalexsanyan 
1- take a look to this issue (https://github.com/miguelbcr/RxPaparazzo/issues/6)
2- it seems to be an issue related with the gallery, maybe not with RxPaparazzo. Anyway you could try to use `RxPaparazzo.single(this).sendToMediaScanner();` in order to notify the gallery when an image is taken/picked up

**Comment by aalexsanyan** [comment]
in #6 you are suggesting to delete the photo ,
but if I only want to display the existing photo and don't have the copy of it and then delete it could 
not display as it's deleting the displaying photo.

I add that code in loadImage() part
file = fileData.file
  File(file?.toURI()).delete()

**Comment by miguelbcr** [comment]
yeah, I'm sorry, this is the way this lib works

**Comment by gukzilla** [comment]
@miguelbcr 
When you select a video file for 500 MB, it takes a very long time to copy. How to avoid this? I do not need to copy the file without the need

**Comment by miguelbcr** [comment]
Originally this lib was thought for photos, after we added other file formats, but we never thought about videos in spite of the lib allows it 😅 . 
How the lib works is making a copy of the original file and the you use it. It was though in this way in case you want to crop the photos, but obviously it doesn't suit for other files than are not images 🙄

**Comment by gukzilla** [comment]
@miguelbcr 
Maybe just add a method dontCopy() in next release? :)

**Comment by miguelbcr** [comment]
yeah, that would be terrific 😄

**Comment by ckpenep** [comment]
Hello. What about dontCopy() method?

**Comment by gukzilla** [comment]
> Hello. What about dontCopy() method?

We had to download the library and expand its boundaries :) I think the easiest way to do it yourself

**Comment by ckpenep** [comment]
Do you have an example for this case?

**Comment by miguelbcr** [comment]
sorry, lately I'm very busy 😓 
why don't you expand the features by doing a PR, then the community can take advantage of this 🤔 and surely they will appreciate your contribution.

**Comment by gukzilla** [comment]
> sorry, lately I'm very busy 
> why don't you expand the features by doing a PR, then the community can take advantage of this  and surely they will appreciate your contribution.

Sorry, the hard NDA does not allow me to open the code
