### ISSUE TITLE
original FileName and FileExtension not found in response?!

### ISSUE THREAD

**Issue by mohopa** [miguelbcr/RxPaparazzo#79]
hi.
thank you for useful library. there is a problem in filename , I want to send file to server so need original fileName but this lib change copied file name and `response.data().getFileName`  is null also `response.data().getTile` some times is null and if exist it has just fileName without extension!
I need file extension too. how I can achieve this?

**Comment by miguelbcr** [comment]
Hi @mohopa,  thanks!
I've tested it and this is the output for a file picked up from gallery:

<img width="653" alt="screen shot 2017-08-26 at 18 28 38" src="https://user-images.githubusercontent.com/2734557/29743212-0bdbec08-8a8d-11e7-9f12-c295a5936d05.png">

As you can see `filename` will give you the information you need, also in `mimeType` you can see the file extension.

Anyway could you provide the steps to reproduce your particular case?,  is a remote file or a local one?, could you attach also a snapshot running the sample app with a breakpoint in the same place?

**Comment by miguelbcr** [comment]
Hi @mohopa did you solve anything?

**Comment by mohopa** [comment]
Hi @miguelbcr 
the mimeType exist in some case , also same for filename and ...
for example in this case I can't get filename:
![image](https://user-images.githubusercontent.com/5052906/30637651-37610586-9e0e-11e7-98b9-7aa9c3614db5.png)
in this one I can't get anything except title(it was a pkg.apk):
![image](https://user-images.githubusercontent.com/5052906/30637683-50b32500-9e0e-11e7-98c4-023489374db6.png)
note that I need real filename and it's extension because rxPaparazzo change name and same it to my directory,I want real name for sending to server.

**Comment by miguelbcr** [comment]
Hi @mohopa!
I'd need all steps you did in order to be able to reproduce that case (type of file, where you pick it up (remote, local, camera,...)). 

Btw, are those screenshots when using sample app? if so, please provide the steps (maybe with a GIF or attaching the conflicting file/s) . If not, use the sample app and try again.

Thanks!

**Comment by mohopa** [comment]
in first picture , I picked file from a folder that create it programmatically on SDCard.
in second one ,I picked file from bluetooth folder on SDCard.
I use it in my app , I will test it in sample app and give you result.

**Comment by mohopa** [comment]
hi again @miguelbcr 
I check it in sample app and got same result :(
(picked file was `pkg.apk` in bluetooth folder on `IntenalStorage`)

![image](https://user-images.githubusercontent.com/5052906/30774173-1df8fc3c-a08b-11e7-9f2d-68e9c028823f.png)

**Comment by miguelbcr** [comment]
Hi @mohopa did you figure anything out?
