### ISSUE TITLE
Feature Request - open a chooserIntent combined with all options

### ISSUE THREAD

**Issue by ndori** [miguelbcr/RxPaparazzo#84]
Hi,
I want to add your library, however I allow in my app to upload a file either with a camera or with the document provider / gallery. 
so what I've done is using Intent.createChooser and adding all the different intents so the user will be able to choose what it desires.

how can it be achieved with your library, or can you add this feature?

Tnx

**Comment by miguelbcr** [comment]
Hi @ndori !
I'm not sure if I've understood your question, maybe you are looking for this -> https://github.com/miguelbcr/RxPaparazzo/issues/47

**Comment by ndori** [comment]
well yes, kinnda, but I don't want to create a dumb dialog, I want to use the default chooser in android, 
I don't use camera permission so I use the camera intent (no need for permission that way) so I allow the user to choose from all of his supporting apps, that is, all camera, all galleries and all document providers...

**Comment by miguelbcr** [comment]
I understand... anyway the camera is launched calling to `new Intent(MediaStore.ACTION_IMAGE_CAPTURE` and this is what its doc says:

> Note: if you app targets M and above and declares as using the CAMERA permission which is not granted, then attempting to use this action will result in a SecurityException.

So `<uses-permission android:name="android.permission.CAMERA"/>` is not needed to use `RxPaparazzo` but if you need add this permission in your app for some reason `RxPaparazzo` will manage it asking for permissions when launching the camera intent.

The other case, I have no idea how to show `RxPaparazzo` into the `Intent.createChooser` maybe it is only suitable for apps that implement this on `Manifest`:
``` 
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
``` 

If you figure something out I'd like to know it

**Comment by ndori** [comment]
yep they changed it in android M... 
anyway, the createChooser can work with intents, if you call an intent for each of those actions you can instead aggregate them. 
I don't know if you can use it in different context...but I will let you know
`		final Intent galleryIntent = getGalleryIntent();


		final Intent chooserIntent = Intent.createChooser(galleryIntent, "select");

		// Add the camera options.
		chooserIntent.putExtra(Intent.EXTRA_INITIAL_INTENTS, cameraIntents.toArray(new Parcelable[cameraIntents.size()]));`

**Comment by ndori** [comment]
I can see you are using intents, in TakePhoto.java you use getIntentCamera()
in order to expose this chooser you need to expose those intents for each of the actions (i.e, camera, gallery, documents....) (maybe some wrapper) that will call it, then when you get the result you need to understand which one should handle it

**Comment by miguelbcr** [comment]
I would appreciate so much if you could do a PR with the changes and an sample how it works

**Comment by miguelbcr** [comment]
I'm going to close it by inactivity. Feel free to reopen it.
Thank you!
