### ISSUE TITLE
Read me update request.

### ISSUE THREAD

**Issue by juanmendez** [miguelbcr/RxPaparazzo#86]
This is a great library, thank you so much!. 
I just wanted to  request how to configure the file provider path.
RxPaparazzo.register(mApplication).withFileProviderPath( "path" );

**Comment by miguelbcr** [comment]
Hi @juanmendez,
Thank you!

You can read [REAMDE.md](https://github.com/miguelbcr/RxPaparazzo/blob/2.x/README.md) under `Setup` section where explains how to configure it and take a look to the `app/` folder to see how it is implemented.

And also this issue could help you -> https://github.com/miguelbcr/RxPaparazzo/issues/64

Let me know it you have any problem
