### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by ZaydelEduard** [miguelbcr/RxPaparazzo#87]
Memory leak happened when pick file from gallery

http://prntscr.com/is0goc

 eventSubscriptions.add(RxPaparazzo.single(this)
                                        .size(ScreenSize())
                                        .usingCamera()
                                        .subscribeOn(Schedulers.io())
                                        .observeOn(AndroidSchedulers.mainThread())
                                        .subscribe({ response ->
                                            if (response.resultCode() == RESULT_OK) {
                                                uploadPhoto(response)
                                            }
                                        }))

unsubscribe onDestroy()

**Comment by miguelbcr** [comment]
Hi @ZaydelEduard !
try to use `response.targetUI().uploadPhoto(response)` instead of `uploadPhoto(response)`

This is a Readme's fragment:

> The generic type of the observable returned by RxPaparazzo when subscribing to any of its features is always an instance of Response class.
> 
> This instance holds a reference to the current Activity/Fragment, accessible calling targetUI() method. Because the original one may be recreated it would be unsafe calling it. Instead, you must call any method/variable of your Activity/Fragment from this instance encapsulated in the response instance.
>
> Also, this instance holds a reference to the data as the appropriate response, as such as the result code of the specific operation.

**Comment by ZaydelEduard** [comment]
The same leak :( 
http://prntscr.com/is5rcv

Code:
eventSubscriptions.add(RxPaparazzo.single(this)
                                        .size(ScreenSize())
                                        .usingCamera()
                                        .subscribeOn(Schedulers.io())
                                        .observeOn(AndroidSchedulers.mainThread())
                                        .subscribe({ response ->
                                            if (response.resultCode() == RESULT_OK) {
                                                response.targetUI().uploadPhoto(response)
                                            }
                                        }))

It's can be reproduced if after choose photo from gallery i very quickly close activity and maybe onNext not called yet. In another cases also leak happened.

**Comment by miguelbcr** [comment]
Maybe you have to call to `eventSubscriptions.dispose()` in your activity `onDestroy()` method 🤔

**Comment by ZaydelEduard** [comment]
> eventSubscriptions.clear()

http://prntscr.com/isee9s

It's not good?

**Comment by miguelbcr** [comment]
yeah, it is good as well.
Does it happen with the sample app?

**Comment by ZaydelEduard** [comment]
Sorry, I did not try.
I just connected the library to my application and tried to use it.

**Comment by ZaydelEduard** [comment]
Thanks for your replies :) You can close issue, my mistake

Fix: eventSubscriptions.clear() must be above onDestroy().

**Comment by miguelbcr** [comment]
thanks for report your solution 👍

**Comment by ZaydelEduard** [comment]
Sorry guys, but issue is still reproduced :( Maybe u can look from your side? The same stack trace as below. Can u reopen pls?

**Comment by miguelbcr** [comment]
Hi!
would you mind to provide a sample code in order to test it. 
You could create a sample project at github and we could work on it, what do you think?
