### ISSUE TITLE
Cannot change file provider path

### ISSUE THREAD

**Issue by sagar091** [miguelbcr/RxPaparazzo#89]
Hello,

While using RxPaparazzo, directory named "RxPaparazzo" created in storage. I don't want to show this directory openly for users, So I change the path from "RxPaparazzo" to ".RxPaparazzo", as a directory with "." cannot be shown by the user.

Another thing is If "." not working then I want to customize that directory name as "ProjectName", but always get error "Error 1 exception occurred" message.

Or we have to use the same file provider path xml as you describe.?

What's the logic behind this file path name.?

**Comment by miguelbcr** [comment]
Hi @sagar091 !
You can take a look to this issue, it could help you -> https://github.com/miguelbcr/RxPaparazzo/issues/64

Or read again this part of the [Readme](https://github.com/miguelbcr/RxPaparazzo#usage)

But if you don't want to make the dir public to the users, you could use `.useInternalStorage()` option:

> By default, the image / file is saved in a directory the same as the app name on the root of the external storage. You can choose to save the images in internal storage by using .useInternalStorage()

**Comment by sagar091** [comment]
Got it. 

Thanks 👍
