### ISSUE TITLE
Failed to find configured root

### ISSUE THREAD

**Issue by drewmahrt** [miguelbcr/RxPaparazzo#94]
I've followed the instructions in the readme, but I seem to be getting the following error:
`Failed to find configured root that contains /data/data/com.example.myapp/files/MyApp/PHOTO-20180920_1422_29861.jpg`

file_paths.xml
```xml
<?xml version="1.0" encoding="utf-8"?>
<paths>
    <files-path name="MyAppImages" path="MyApp"/>
</paths>
```

In my Application subclass:
```kotlin
       
RxPaparazzo.register(this)
        .withFileProviderPath("MyApp")
        .withFileProviderAuthority(BuildConfig.APPLICATION_ID+".file_provider");
```

In my manifest (inside of the application tag):
```xml
<provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}.file_provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths" />
 </provider>
```

**Comment by miguelbcr** [comment]
Hi @drewmahrt !
It seems to be all OK, I remember a similar  issue -> https://github.com/miguelbcr/RxPaparazzo/issues/64#issuecomment-283917070 

Anyway try to remove `.withFileProviderAuthority(BuildConfig.APPLICATION_ID+".file_provider");` since it is the same authority.

Other option is to change the path value (in `rx_paparazzo_file_paths.xml` and setting `.withFileProviderPath("MyApp")` only)  on the sample app and see what happen.

**Comment by drewmahrt** [comment]
Thanks for the quick reply!

Changing the path in the sample app worked fine, but removing the `withFileProviderAuthority` resulted in the same error in my app.

My app uses id suffixes in gradle for each product flavor. Would that affect anything?

```
local  {
    ...
    applicationIdSuffix ".local"
}

staging {
    ...
    applicationIdSuffix ".local"
}

prod {
    ...
    applicationIdSuffix ".local"
}
```

**Comment by miguelbcr** [comment]
hmm, maybe 🤔because in your error you got:
```
Failed to find configured root that contains /data/data/com.example.myapp/files/MyApp/PHOTO-20180920_1422_29861.jpg 
```

where it seems that `.local` suffix is missing

 try to use `Context.getPackageName()` instead or to put it explicitly 
``` 
.withFileProviderAuthority("com.example.myapp.file_provider") 
```

**Comment by drewmahrt** [comment]
I resolved the issue by adding my file_paths.xml to each of the flavor directories in the project.

**Comment by miguelbcr** [comment]
Great! 
Thanks for sharing the solution! 👏
