### ISSUE TITLE
androidX

### ISSUE THREAD

**Issue by vitalyermolovich** [miguelbcr/RxPaparazzo#96]
When wiil it be on AndroidX ?

**Comment by miguelbcr** [comment]
Thanks @vitalyermolovich !
I didn't have the chance of checking it on AndroidX, is it not working?

I hope next week spend some time to review the oppened issues.

**Comment by miguelbcr** [comment]
sorry I thought it was a new Android version 😅but it is the new support library. I found this article very useful -> https://medium.com/ta-tonthongkam/android-jetpack-android-x-36c73abff1c5

yeah, I think I could do the migration, but not right now 🙄 , before I'd like to address the issues and also migrate the lib to kotlin.
